/*
 * generated by Xtext 2.10.0
 */
package fr.mleduc.ui.tests;

import com.google.inject.Injector;
import fr.mleduc.mmlang.ui.internal.MmlangActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class MMLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MmlangActivator.getInstance().getInjector("fr.mleduc.MMLang");
	}

}
