/*
 * generated by Xtext 2.10.0
 */
package fr.mleduc.ui;

import com.google.inject.Injector;
import fr.mleduc.mlang.ui.internal.MlangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MlangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MlangActivator.getInstance().getInjector(MlangActivator.FR_MLEDUC_MLANG);
	}
	
}
