/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc;

import fr.mleduc.AbstractMLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MLangRuntimeModule extends AbstractMLangRuntimeModule {
}
