/*
 * generated by Xtext 2.10.0
 */
package fr.mleduc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MLangStandaloneSetup extends MLangStandaloneSetupGenerated {

	def static void doSetup() {
		new MLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
