/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.csv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.csv.CsvPackage#getStringCell()
 * @model
 * @generated
 */
public interface StringCell extends Cell
{
} // StringCell
