/**
 * generated by Xtext 2.10.0
 */
package variable.cs.validation;

import variable.cs.validation.AbstractVarLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VarLangValidator extends AbstractVarLangValidator {
}
