<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expr_cst_mult_add" nsURI="http://multadd.multaddlang/expr_cst_mult_add/" nsPrefix="add">
  <eClassifiers xsi:type="ecore:EClass" name="Expr" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cst" eSuperTypes="//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
