/*
 * generated by Xtext 2.10.0
 */
package fr.mleduc.parser.antlr;

import com.google.inject.Inject;
import fr.mleduc.parser.antlr.internal.InternalExplicitOperationsParser;
import fr.mleduc.services.ExplicitOperationsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ExplicitOperationsParser extends AbstractAntlrParser {

	@Inject
	private ExplicitOperationsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExplicitOperationsParser createParser(XtextTokenStream stream) {
		return new InternalExplicitOperationsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ExplicitOperationsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExplicitOperationsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
