/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.mMLang.impl;

import fr.mleduc.mMLang.CardInf;
import fr.mleduc.mMLang.MMLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Card Inf</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CardInfImpl extends CardImpl implements CardInf
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CardInfImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MMLangPackage.Literals.CARD_INF;
  }

} //CardInfImpl
