/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.mMLang.impl;

import fr.mleduc.mMLang.Card;
import fr.mleduc.mMLang.MMLangPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Card</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CardImpl extends MinimalEObjectImpl.Container implements Card
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MMLangPackage.Literals.CARD;
  }

} //CardImpl
