/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.coldLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facet Composition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.coldLang.FacetComposition#getPerspectiveLanguage <em>Perspective Language</em>}</li>
 *   <li>{@link fr.mleduc.coldLang.FacetComposition#getApplication <em>Application</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.coldLang.ColdLangPackage#getFacetComposition()
 * @model
 * @generated
 */
public interface FacetComposition extends EObject
{
  /**
   * Returns the value of the '<em><b>Perspective Language</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Perspective Language</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Perspective Language</em>' reference.
   * @see #setPerspectiveLanguage(PerspectiveLanguage)
   * @see fr.mleduc.coldLang.ColdLangPackage#getFacetComposition_PerspectiveLanguage()
   * @model
   * @generated
   */
  PerspectiveLanguage getPerspectiveLanguage();

  /**
   * Sets the value of the '{@link fr.mleduc.coldLang.FacetComposition#getPerspectiveLanguage <em>Perspective Language</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Perspective Language</em>' reference.
   * @see #getPerspectiveLanguage()
   * @generated
   */
  void setPerspectiveLanguage(PerspectiveLanguage value);

  /**
   * Returns the value of the '<em><b>Application</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Application</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Application</em>' containment reference.
   * @see #setApplication(Application)
   * @see fr.mleduc.coldLang.ColdLangPackage#getFacetComposition_Application()
   * @model containment="true"
   * @generated
   */
  Application getApplication();

  /**
   * Sets the value of the '{@link fr.mleduc.coldLang.FacetComposition#getApplication <em>Application</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Application</em>' containment reference.
   * @see #getApplication()
   * @generated
   */
  void setApplication(Application value);

} // FacetComposition
