/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.coldLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.coldLang.Model#getConcerns <em>Concerns</em>}</li>
 *   <li>{@link fr.mleduc.coldLang.Model#getLanguages <em>Languages</em>}</li>
 *   <li>{@link fr.mleduc.coldLang.Model#getPerspectives <em>Perspectives</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.coldLang.ColdLangPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Concerns</b></em>' containment reference list.
   * The list contents are of type {@link fr.mleduc.coldLang.Concern}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concerns</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concerns</em>' containment reference list.
   * @see fr.mleduc.coldLang.ColdLangPackage#getModel_Concerns()
   * @model containment="true"
   * @generated
   */
  EList<Concern> getConcerns();

  /**
   * Returns the value of the '<em><b>Languages</b></em>' containment reference list.
   * The list contents are of type {@link fr.mleduc.coldLang.Language}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Languages</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Languages</em>' containment reference list.
   * @see fr.mleduc.coldLang.ColdLangPackage#getModel_Languages()
   * @model containment="true"
   * @generated
   */
  EList<Language> getLanguages();

  /**
   * Returns the value of the '<em><b>Perspectives</b></em>' containment reference list.
   * The list contents are of type {@link fr.mleduc.coldLang.Perspective}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Perspectives</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Perspectives</em>' containment reference list.
   * @see fr.mleduc.coldLang.ColdLangPackage#getModel_Perspectives()
   * @model containment="true"
   * @generated
   */
  EList<Perspective> getPerspectives();

} // Model
