/*
 * generated by Xtext 2.10.0
 */
package fr.mleduc.parser.antlr;

import com.google.inject.Inject;
import fr.mleduc.parser.antlr.internal.InternalCsvParser;
import fr.mleduc.services.CsvGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CsvParser extends AbstractAntlrParser {

	@Inject
	private CsvGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCsvParser createParser(XtextTokenStream stream) {
		return new InternalCsvParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CsvGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CsvGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
