/**
 * generated by Xtext 2.10.0
 */
package varadd.cs.validation;

import varadd.cs.validation.AbstractVarAddLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VarAddLangValidator extends AbstractVarAddLangValidator {
}
