/*
 * generated by Xtext 2.10.0
 */
package variable.cs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VarLangStandaloneSetup extends VarLangStandaloneSetupGenerated {

	def static void doSetup() {
		new VarLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
