/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.mMLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Card</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.mMLang.MMLangPackage#getCard()
 * @model
 * @generated
 */
public interface Card extends EObject
{
} // Card
