/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.mMLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generic</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.mleduc.mMLang.MMLangPackage#getGeneric()
 * @model
 * @generated
 */
public interface Generic extends Reference
{
} // Generic
