/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.mMLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metamodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.mMLang.Metamodel#isConcrete <em>Concrete</em>}</li>
 *   <li>{@link fr.mleduc.mMLang.Metamodel#getName <em>Name</em>}</li>
 *   <li>{@link fr.mleduc.mMLang.Metamodel#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.mMLang.MMLangPackage#getMetamodel()
 * @model
 * @generated
 */
public interface Metamodel extends EObject
{
  /**
   * Returns the value of the '<em><b>Concrete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concrete</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concrete</em>' attribute.
   * @see #setConcrete(boolean)
   * @see fr.mleduc.mMLang.MMLangPackage#getMetamodel_Concrete()
   * @model
   * @generated
   */
  boolean isConcrete();

  /**
   * Sets the value of the '{@link fr.mleduc.mMLang.Metamodel#isConcrete <em>Concrete</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concrete</em>' attribute.
   * @see #isConcrete()
   * @generated
   */
  void setConcrete(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.mleduc.mMLang.MMLangPackage#getMetamodel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.mleduc.mMLang.Metamodel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Classes</b></em>' containment reference list.
   * The list contents are of type {@link fr.mleduc.mMLang.Class}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Classes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classes</em>' containment reference list.
   * @see fr.mleduc.mMLang.MMLangPackage#getMetamodel_Classes()
   * @model containment="true"
   * @generated
   */
  EList<fr.mleduc.mMLang.Class> getClasses();

} // Metamodel
