/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.ui;

import fr.mleduc.ui.AbstractCsvUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CsvUiModule extends AbstractCsvUiModule {
  public CsvUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
