/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.explicitOperations;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Artifact Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.explicitOperations.ArtifactParameter#getName <em>Name</em>}</li>
 *   <li>{@link fr.mleduc.explicitOperations.ArtifactParameter#getArtifact <em>Artifact</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.explicitOperations.ExplicitOperationsPackage#getArtifactParameter()
 * @model
 * @generated
 */
public interface ArtifactParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(LanguageDependency)
   * @see fr.mleduc.explicitOperations.ExplicitOperationsPackage#getArtifactParameter_Name()
   * @model
   * @generated
   */
  LanguageDependency getName();

  /**
   * Sets the value of the '{@link fr.mleduc.explicitOperations.ArtifactParameter#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(LanguageDependency value);

  /**
   * Returns the value of the '<em><b>Artifact</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Artifact</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifact</em>' reference.
   * @see #setArtifact(Referentiable)
   * @see fr.mleduc.explicitOperations.ExplicitOperationsPackage#getArtifactParameter_Artifact()
   * @model
   * @generated
   */
  Referentiable getArtifact();

  /**
   * Sets the value of the '{@link fr.mleduc.explicitOperations.ArtifactParameter#getArtifact <em>Artifact</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifact</em>' reference.
   * @see #getArtifact()
   * @generated
   */
  void setArtifact(Referentiable value);

} // ArtifactParameter
