/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.explicitOperations;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.mleduc.explicitOperations.Not#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see fr.mleduc.explicitOperations.ExplicitOperationsPackage#getNot()
 * @model
 * @generated
 */
public interface Not extends Proposition
{
  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Next</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(Proposition)
   * @see fr.mleduc.explicitOperations.ExplicitOperationsPackage#getNot_Next()
   * @model containment="true"
   * @generated
   */
  Proposition getNext();

  /**
   * Sets the value of the '{@link fr.mleduc.explicitOperations.Not#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(Proposition value);

} // Not
