/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc;

import fr.mleduc.CsvStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CsvStandaloneSetup extends CsvStandaloneSetupGenerated {
  public static void doSetup() {
    CsvStandaloneSetup _csvStandaloneSetup = new CsvStandaloneSetup();
    _csvStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
