/**
 * generated by Xtext 2.10.0
 */
package fr.mleduc.explicitOperations.impl;

import fr.mleduc.explicitOperations.CardVal0;
import fr.mleduc.explicitOperations.ExplicitOperationsPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Card Val0</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CardVal0Impl extends CardValImpl implements CardVal0
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CardVal0Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExplicitOperationsPackage.Literals.CARD_VAL0;
  }

} //CardVal0Impl
